In [1]:
import gene_ex_encoder_upgraded as ge

number = [10.34200]
ge.value(number, 6)

array([[10.342]])

In [2]:
number = [1.34200]
ge.one_hot(number, max_int=1, decimal_points=3)

array([[1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
number = [1.3]
ge.one_hot(number, max_int=1, decimal_points=6)

array([[1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
number = [12.94209]
ge.binary(number, max_int=10, decimal_points=5)

array([[1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 0, 1]])

In [100]:
def tenfold_binary(gene_e: list, decimal_points: int=1, max_int: int=10, decimals_to_int: int=None) -> np.array:
        if decimals_to_int == None: decimals_to_int = decimal_points
        decimal_points = decimal_points - decimals_to_int
        out=[]
        for sample in gene_e:
            sample = sample * 10**decimals_to_int
            sample=float(f"%.{decimal_points}f" % sample)
            int_lenth = len(bin(max_int*(10**decimals_to_int))[2:]) if max_int != 0 else len(bin(10**decimals_to_int)[2:])
            bit = 1+int_lenth+4*(decimal_points)
            vector= [0] * bit
            
            if sample > 0:
                vector[0] = 1
            else:
                sample = -sample
            
            vector[1+int_lenth-len(bin(int(sample))[2:]):int_lenth+1] = [int(j) for j in bin(int(sample))[2:]]

            
            for decimal in range(1, decimal_points+1):
                if sample*decimal - int(sample*decimal) != 0:
                    value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                    index_begin = (1+int_lenth+4*decimal) - len(bin(value)[2:])
                    index_end = (1+int_lenth+4*decimal)
                    vector[index_begin:index_end] = [int(j) for j in bin(int(value))[2:]]

            out.append(vector)
        return np.array(out)

# number = [12.94209]
# number = [1.33]
number = [0.392003]
r= tenfold_binary(number, max_int=0, decimal_points=6)[0][1:]
r
binary_string, binary_value = binary(r)

print(r)
print(binary_value)

[0 1 0 1 1 1 1 1 1 0 1 1 0 1 0 0 0 0 1 1]
392003


In [78]:
# number = [12.94209]
# number = [1.33]
number = [0.3]
r= ge.tenfold_binary(number, max_int=10, decimal_points=2)[0][1:]
r
binary_string, binary_value = binary(r)

print(r)
print(binary_value)

[0 0 0 0 0 1 1 1 1 0]
30


In [55]:
import numpy as np

def binary(arr):
    # Flatten the 2D array to 1D
    flat_arr = arr.flatten()
    # Join the elements as a binary string
    binary_str = ''.join(str(i) for i in flat_arr)
    # Convert the binary string into an integer
    result = int(binary_str, 2)
    return binary_str, result

# Example usage
# array = np.array([[1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1]])
binary_string, binary_value = binary(r)
print("Binary String:", binary_string)
print("Integer Value:", binary_value)


Binary String: 00010100111111
Integer Value: 1343


In [34]:
int(1.342*1000).bit_length()

11

In [24]:
def one_hot_original(gene_e,bit=25, t=10):
        out=[]
        for i in gene_e:
            i=float("%.1f" % i)
            a=[0]*bit
            if i>0:
                a[0]=1
                a[int(i)] = 1
                if i-int(i)!=0:
                    a[int(i*t-int(i)*t)+15] = 1
            if i<0:
                
                a[abs(int(i))] = 1
                if i-int(i)!=0:
                    a[abs(int(i*t-int(i)*t))+15] = 1
            out.append(a)
        return np.array(out)

number = [10.3]
one_hot_original(number)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0]])

In [25]:
import numpy as np

def value(gene_e: list, decimal_points: int = 6) -> np.array:
    out = []
    for sample in gene_e:
        # Convert to float (ensuring numerical value)
        sample_float = float(sample)
        # Append formatted string representation
        formatted = f"{sample_float:.{decimal_points}f}"
        out.append([formatted])
    return np.array(out, dtype=str)  # Return array of formatted strings

number = [10.320000001]
a = ge.value(number, 6)
a

array([[10.32]])

a[0][0]

In [1]:
import torch

def tenfold_binary(gene_e: list, decimal_points: int = 1, max_int: int = 10, decimals_to_int: int = None) -> torch.Tensor:
    # Check CUDA availability
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Running on: {device}")

    # Convert input list to a PyTorch tensor and move to GPU if available
    gene_e_tensor = torch.tensor(gene_e, device=device, dtype=torch.float32)

    if decimals_to_int is None:
        decimals_to_int = decimal_points
    decimal_points = decimal_points - decimals_to_int

    # Precompute constants on the same device
    scale_factor = 10 ** decimals_to_int
    max_binary_length = len(bin(max_int * (10**decimals_to_int))[2:]) if max_int != 0 else len(bin(10**decimals_to_int)[2:])
    bit = 1 + max_binary_length + 4 * decimal_points

    # Initialize output tensor
    output = torch.zeros((gene_e_tensor.size(0), bit), device=device, dtype=torch.int32)

    # Main computation
    for i, sample in enumerate(gene_e_tensor):
        # Scale and truncate decimals
        sample_scaled = sample * scale_factor
        sample_scaled = torch.round(sample_scaled * 10**(-decimal_points)) * 10**decimal_points

        # Determine positivity/negativity
        if sample_scaled > 0:
            output[i, 0] = 1
        else:
            sample_scaled = -sample_scaled

        # Convert integer part to binary
        int_part = int(sample_scaled)
        binary_int = torch.tensor([int(b) for b in bin(int_part)[2:]], device=device)
        output[i, 1 + max_binary_length - binary_int.size(0):1 + max_binary_length] = binary_int

        # Process decimal points
        for decimal in range(1, decimal_points + 1):
            value = int((sample_scaled * 10**decimal) % 10)
            binary_value = torch.tensor([int(b) for b in bin(value)[2:]], device=device)
            start_idx = 1 + max_binary_length + 4 * decimal - binary_value.size(0)
            end_idx = 1 + max_binary_length + 4 * decimal
            output[i, start_idx:end_idx] = binary_value

    return output

# Example usage
gene_e = [1.23, 4.56, 7.89]
result = tenfold_binary(gene_e)
print(result)


Running on: cuda
tensor([[1, 0, 0, 0, 1, 1, 0, 0],
        [1, 0, 1, 0, 1, 1, 1, 0],
        [1, 1, 0, 0, 1, 1, 1, 1]], device='cuda:0', dtype=torch.int32)


In [5]:
import numpy as np

def tenfold_binary(gene_e: list, decimal_points: int=1, max_int: int=10, decimals_to_int: int=None) -> np.array:
        if decimals_to_int == None: decimals_to_int = decimal_points
        decimal_points = decimal_points - decimals_to_int
        out=[]
        for sample in gene_e:
            sample = sample * 10**decimals_to_int
            sample=float(f"%.{decimal_points}f" % sample)
            int_lenth = len(bin(max_int*(10**decimals_to_int))[2:]) if max_int != 0 else len(bin(10**decimals_to_int)[2:])
            bit = 1+int_lenth+4*(decimal_points)
            vector= [0] * bit
            
            if sample > 0:
                vector[0] = 1
            else:
                sample = -sample
            
            vector[1+int_lenth-len(bin(int(sample))[2:]):int_lenth+1] = [int(j) for j in (bin(int(sample))[2:])]

            
            for decimal in range(1, decimal_points+1):
                if sample*decimal - int(sample*decimal) != 0:
                    value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                    index_begin = (1+int_lenth+4*decimal) - len(bin(value)[2:])
                    index_end = (1+int_lenth+4*decimal)
                    vector[index_begin:index_end] = [int(j) for j in (bin(int(value))[2:])]

            out.append(vector)
        return np.array(out)


# Check CUDA availability
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Running on: {device}")

gene_e = [1.23, 4.56, 7.89]
gene_e_tensor = torch.tensor(gene_e, device=device, dtype=torch.float32)

result = tenfold_binary(gene_e_tensor)
print(result)

Running on: cuda
[[1 0 0 0 1 1 0 0]
 [1 0 1 0 1 1 1 0]
 [1 1 0 0 1 1 1 1]]


In [26]:
def tenfold_binary(gene_e: list, decimal_points: int=1, max_int: int=10, decimals_to_int: int=None) -> np.array:
        if decimals_to_int == None: decimals_to_int = decimal_points
        decimal_points = decimal_points - decimals_to_int
        out=[]
        for sample in gene_e:
            sample = sample * 10**decimals_to_int
            print(decimal_points)
            sample=float(f"%.{decimal_points}f" % sample)
            int_lenth = len(bin(max_int*(10**decimals_to_int))[2:]) if max_int != 0 else len(bin(10**decimals_to_int)[2:])
            bit = 1+int_lenth+4*(decimal_points)
            vector= [0] * bit
            
            if sample > 0:
                vector[0] = 1
            else:
                sample = -sample
            
            vector[1+int_lenth-len(bin(int(sample))[2:]):int_lenth+1] = [int(j) for j in (bin(int(sample))[2:])]

            
            for decimal in range(1, decimal_points+1):
                if sample*decimal - int(sample*decimal) != 0:
                    value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                    index_begin = (1+int_lenth+4*decimal) - len(bin(value)[2:])
                    index_end = (1+int_lenth+4*decimal)
                    vector[index_begin:index_end] = [int(j) for j in (bin(int(value))[2:])]

            out.append(vector)
        return np.array(out)

g = [0.234]
tenfold_binary(g, max_int=10, decimal_points=3)

0


array([[1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0]])

In [39]:
max_int = 0
decimal_points = 3


( 1 + (10**(decimal_points+1)).bit_length() if max_int != 0 else (10**(decimal_points)).bit_length())

14

In [23]:
float(f"%.{4}f" % 23.4322)

23.4322

ValueError: unsupported format character '-' (0x2d) at index 2

In [ ]:
import gene_ex_encoder_upgraded as ge



ValueError: unsupported format character '-' (0x2d) at index 2

In [11]:
bin(234)

'0b11101010'

In [1]:
3

3

In [3]:
path = '../data/df_fame_test.csv'

import pandas as pd

df = pd.read_csv(path)

In [11]:
for mol in df.smiles:
    print('Molécula: ', mol)

Molécula:  C[C@@H]1CC2C3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO
Molécula:  CC(=O)OCC(=O)[C@@]1(O)[C@H](C)C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@@]21C
Molécula:  C[C@]12CCC3C(CCC4=CC(=O)CC[C@@]43C)C1CC[C@@H]2O
Molécula:  CCC(=O)O[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C
Molécula:  C[C@@H]1CC2C3CCC4=CC(=O)C=CC4(C)[C@]3(F)[C@@H](O)CC2(C)[C@]1(O)C(=O)CO
Molécula:  C[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@@]21C
Molécula:  C[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@@]21C
Molécula:  CC(=O)OCC(=O)[C@@]1(O)[C@H](C)C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@@]21C
Molécula:  CCC(=O)O[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C
Molécula:  C[C@@H]1CC2C3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO
Molécula:  CC(=O)OCC(=O)[C@@]1(O)[C@H](C)C[C@H]2[C@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@@]21C
Molécula:  C[C@H]1C[C@H]2[C@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@

In [23]:
import numpy as np 

def debug_one_hot(gene_e: list, decimal_points: int=1, max_int: int=10, numbers_size: int=9) -> np.array:
        out=[]
        for sample in gene_e:
             bit = (1+max_int+numbers_size*decimal_points+1)
             sample = float(f"%.{decimal_points}f" % sample)
             vector = [0]*bit

             if sample > 0:
                 vector[0] = 1
             else:
                  sample = -sample

             vector[abs(int(sample)-max_int)+1] = 1

             for decimal in range(1, decimal_points+1):
                    if sample*decimal - int(sample*decimal) != 0:
                       value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                       if (value != 10) & (value != 0):
                        index = 1+max_int+numbers_size*(decimal-1)+value
                        vector[index] = 1
             out.append(vector)

        return np.array(out)

gene_e=[0.000]
len(debug_one_hot(gene_e, decimal_points=1, max_int=0)[0])

11

In [34]:
cell_types_length = 2
max_int = 0
decimal_points=1
gene_e=[0.000]

print(cell_types_length + ( 1 + (max_int+1) + 9*decimal_points))
print(cell_types_length + 1 + len(debug_one_hot(gene_e, decimal_points=decimal_points, max_int=max_int)[0]))
print(len(debug_one_hot(gene_e, decimal_points=decimal_points, max_int=max_int)[0]))

13
14
11
