In [ ]:
import pandas as pd

df_tran = pd.read_csv('data/subLINCS_train.csv')
df_fame = pd.read_csv('data/FAME_dataset_train.csv')

In [ ]:
print('TRANSGEM_train: 25364')
print('FAME_train: 25658')

print('TRANSGEM_test: 14')
print('FAME_test: 3291')

print('TRANSGEM_val: 2000')
print('FAME_val: 2872')

In [12]:
df_tran

cell_line   dose        drug_id  \
0         MCF7  10 uM  BRD-K33226500   
1         MCF7  10 uM  BRD-K71035033   
2         MCF7  10 uM  BRD-A01320529   
3         MCF7  10 uM  BRD-K55424922   
4         MCF7  10 uM  BRD-K56403959   
...        ...    ...            ...   
1995     HEPG2  10 uM  BRD-K85133207   
1996     HEPG2  10 uM  BRD-K83354763   
1997     HEPG2  10 uM  BRD-K97399794   
1998     HEPG2  10 uM  BRD-A28105619   
1999     HEPG2  10 uM  BRD-K73881242   

                                                 smiles  \
0     CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...   
1     CN1CCN(Cc2ccc(cc2)C(=O)Nc2ccc(C)c(Nc3nc(cs3)-c...   
2                OCc1cc(ccc1O)C(O)CNCCCCCCOCCCCc1ccccc1   
3                                 Clc1cccc(SC2CCNCC2)n1   
4                  OCCOCCN1CCN(Cc2cccc(Oc3ccccc3)c2)CC1   
...                                                 ...   
1995  CC(=O)N[C@H]1C[C@H](C1)C(=O)Nc1cc(ccc1N)-c1ccc...   
1996                         Cc1ccc(NCCCc2ccccc2)c(N)c1   
1997         Oc1cc(O)c2c(c1)oc(-c1ccc(O)c(O)c1)c(O)c2=O   
1998  CC(C)(O)C=CC(=O)[C@](C)(O)C1[C@H](O)C[C@@]2(C)...   
1999  CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...   

                                                selfies  \
0     ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   
1     ['[C]', '[N]', '[C]', '[C]', '[N]', '[Branch2_...   
2     ['[O]', '[C]', '[C]', '[=C]', '[C]', '[Branch1...   
3     ['[Cl]', '[C]', '[=C]', '[C]', '[=C]', '[C]', ...   
4     ['[O]', '[C]', '[C]', '[O]', '[C]', '[C]', '[N...   
...                                                 ...   
1995  ['[C]', '[C]', '[Branch1_2]', '[C]', '[=O]', '...   
1996  ['[C]', '[C]', '[=C]', '[C]', '[=C]', '[Branch...   
1997  ['[O]', '[C]', '[=C]', '[C]', '[Branch1_1]', '...   
1998  ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   
1999  ['[C]', '[C]', '[O]', '[C]', '[Branch1_2]', '[...   

                                                 gene_e  
0     -0.0//0.1//0.1//0.1//0.1//-0.0//0.0//0.1//-0.1...  
1     0.5//-0.1//-0.1//0.1//0.2//0.0//0.3//-0.0//-0....  
2     0.3//-0.1//-0.5//-0.1//0.8//0.3//0.1//-0.0//-0...  
3     0.0//-0.4//0.2//0.2//0.1//-0.0//-0.1//-0.0//0....  
4     -0.1//-0.0//0.1//0.0//-0.3//0.1//0.1//0.4//-0....  
...                                                 ...  
1995  0.2//-0.2//0.5//-0.1//0.6//1.0//0.0//0.2//0.0/...  
1996  0.4//0.0//0.5//0.2//-0.0//0.2//0.1//0.0//0.0//...  
1997  0.1//0.2//0.3//-0.7//-0.0//0.8//0.2//-0.1//-0....  
1998  0.5//-0.3//0.1//-0.2//-0.2//-0.1//-1.2//-0.8//...  
1999  0.1//-0.1//-0.1//0.5//1.1//0.3//-0.1//-0.1//-0...  

[2000 rows x 6 columns]

In [38]:
print(df_fame.gene_e.nunique())
print(len(df_fame.gene_e))
print(df_fame.smiles.nunique())

print(df_fame.smiles.nunique()/df_fame.gene_e.nunique())

25658
25658
16019
0.6243276950658664


In [39]:
df_tran.smiles               # 25364
df_tran.smiles.nunique()     # 6797

print(df_tran.gene_e.nunique())
print(len(df_tran.gene_e))

print(df_tran.smiles.nunique()/df_tran.gene_e.nunique())

25362
25364
0.2679993691349263


In [113]:
df_tran_test = pd.read_csv('data/subLINCS_test.csv')
df_fame_test = pd.read_csv('data/FAME_dataset_test.csv')

df_tran_val = pd.read_csv('data/subLINCS_val.csv')
df_fame_val = pd.read_csv('data/FAME_dataset_val.csv')

In [117]:
def info(df, name, col='gene_e'):
    print(f'======== {name} with {col} ========\n')
    print('Smiles number total: ', len(df.smiles))               # 25364
    print('Smiles number unique: ', df.smiles.nunique())     # 6797

    print('Gene number total: ', len(df[col]))
    print('Gene number unique: ', df[col].nunique())

    print('Proportion of simles per gene: ', df.smiles.nunique()/df[col].nunique())
    print('\n\n')

info(df_tran, 'df_tran')
info(df_fame, 'df_fame')
info(df_fame, 'df_fame', col='gene_e_simplified')

info(df_tran_test, 'df_tran_test')
info(df_fame_test, 'df_fame_test')
info(df_fame_test, 'df_fame_test', col='gene_e_simplified')

info(df_tran_val, 'df_tran_val')
info(df_fame_val, 'df_fame_val')
info(df_fame_val, 'df_fame_val', col='gene_e_simplified')

======== df_tran with gene_e ========

Smiles number total:  25364
Smiles number unique:  6797
Gene number total:  25364
Gene number unique:  25362
Proportion of simles per gene:  0.2679993691349263



======== df_fame with gene_e ========

Smiles number total:  25658
Smiles number unique:  16019
Gene number total:  25658
Gene number unique:  25658
Proportion of simles per gene:  0.6243276950658664



======== df_fame with gene_e_simplified ========

Smiles number total:  25658
Smiles number unique:  16019
Gene number total:  25658
Gene number unique:  25658
Proportion of simles per gene:  0.6243276950658664



======== df_tran_test with gene_e ========

Smiles number total:  14
Smiles number unique:  13
Gene number total:  14
Gene number unique:  14
Proportion of simles per gene:  0.9285714285714286



======== df_fame_test with gene_e ========

Smiles number total:  3291
Smiles number unique:  1980
Gene number total:  3291
Gene number unique:  3291
Proportion of simles per gene:  0.6

In [114]:
def put_in_one_decimal(k):
        return [[f'%.1f' % sample for sample in li] for li in k]

def gene_simplification(genes):
    gene_List = [[float(j) for j in i.split("//")] for i in genes]

    gene_List_changed = put_in_one_decimal(gene_List)

    k = ['//'.join(sample) for sample in gene_List_changed]
    k = pd.Series(k).str.replace('-0.0', '0.0')

    return k

In [115]:
df_fame['gene_e_simplified'] = gene_simplification(df_fame['gene_e'])
df_fame_test['gene_e_simplified'] = gene_simplification(df_fame_test['gene_e'])
df_fame_val['gene_e_simplified'] = gene_simplification(df_fame_val['gene_e'])

C:\Users\Acer\AppData\Local\Temp\ipykernel_16848\642220309.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  k = pd.Series(k).str.replace('-0.0', '0.0')
C:\Users\Acer\AppData\Local\Temp\ipykernel_16848\642220309.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  k = pd.Series(k).str.replace('-0.0', '0.0')
C:\Users\Acer\AppData\Local\Temp\ipykernel_16848\642220309.py:10: FutureWarning: The default value of regex will change from True to False in a future version.
  k = pd.Series(k).str.replace('-0.0', '0.0')


In [108]:
df_fame['gene_e_original'] = df_fame['gene_e']
df_fame['gene_e'] = k

In [109]:
df_fame

smiles  \
0      COc1ccccc1NC(=O)N1CCCCN2[C@H](C1)[C@H](c1ccc(-...   
1      CO[C@H]1CN(C)C(=O)c2ccc(NC(=O)C3CCCC3)cc2OC[C@...   
2                                CCN(CC)C(=O)c1cccc(C)c1   
3      COC(=O)N1CCN(C(=O)Cc2ccc(Cl)c(Cl)c2)C(CN2CCCC2)C1   
4      COc1cccc(S(=O)(=O)N(C)C[C@@H]2Oc3cc(C4=CCCC4)c...   
...                                                  ...   
25653  C[C@@H]1CCCCO[C@@H](CN(C)C(=O)Nc2ccccc2)[C@H](...   
25654     O=C(CNc1cccc2ccccc12)NN=Cc1ccc([N+](=O)[O-])o1   
25655  COc1ccc2c3c(n(C)c2c1)[C@H](CO)NCC31CN(Cc2cc(-c...   
25656  COc1ccc2c3c([nH]c2c1)[C@H](CO)N(C(=O)C1CCOCC1)...   
25657  COc1ccc(C2Nc3ccccc3C(=O)N2Cc2ccco2)cc1COc1ccccc1C   

                                                 selfies  \
0      [C][O][C][=C][C][=C][C][=C][Ring1][=Branch1][N...   
1      [C][O][C@H1][C][N][Branch1][C][C][C][=Branch1]...   
2      [C][C][N][Branch1][Ring1][C][C][C][=Branch1][C...   
3      [C][O][C][=Branch1][C][=O][N][C][C][N][Branch2...   
4      [C][O][C][=C][C][=C][C][Branch2][Branch1][=Bra...   
...                                                  ...   
25653  [C][C@@H1][C][C][C][C][O][C@@H1][Branch2][Ring...   
25654  [O][=C][Branch1][P][C][N][C][=C][C][=C][C][=C]...   
25655  [C][O][C][=C][C][=C][C][=C][Branch1][O][N][Bra...   
25656  [C][O][C][=C][C][=C][C][=C][Branch1][Branch2][...   
25657  [C][O][C][=C][C][=C][Branch2][Ring1][#Branch2]...   

                                                  gene_e  \
0      -0.1//0.0//0.1//-0.1//0.1//-0.1//0.2//-0.1//-0...   
1      0.1//0.0//-0.1//0.1//-0.2//0.0//0.0//0.1//0.0/...   
2      0.1//0.0//-0.1//0.0//0.0//0.0//0.1//0.0//0.1//...   
3      0.1//0.0//0.0//0.0//0.2//0.0//0.2//-0.1//0.0//...   
4      0.1//-0.2//0.1//0.2//-0.3//0.0//0.0//0.0//0.0/...   
...                                                  ...   
25653  -0.1//-0.1//0.0//-0.1//0.0//0.1//0.2//-0.1//-0...   
25654  -0.1//0.2//0.2//0.0//0.1//-0.1//0.1//-0.1//0.2...   
25655  0.0//-0.1//0.1//0.1//-0.3//-0.1//0.0//-0.1//0....   
25656  0.1//0.0//0.1//0.1//0.0//-0.1//0.0//0.0//-0.1/...   
25657  0.0//0.0//0.1//0.1//0.0//0.1//0.3//-0.1//0.0//...   

                                         gene_e_original  
0      -0.081911//0.023442//0.118003//-0.118417//0.06...  
1      0.068768//-0.010101//-0.121707//0.142479//-0.1...  
2      0.094386//0.013693//-0.124994//-0.000583//0.02...  
3      0.085143//0.031898//0.043786//-0.038682//0.188...  
4      0.111219//-0.157678//0.085092//0.155815//-0.27...  
...                                                  ...  
25653  -0.081926//-0.054207//0.049499//-0.067319//-0....  
25654  -0.084058//0.171540//0.165466//-0.043218//0.11...  
25655  -0.008801//-0.091641//0.055367//0.077171//-0.2...  
25656  0.053546//-0.034953//0.096325//0.090061//-0.02...  
25657  0.041853//0.010516//0.050944//0.091727//-0.034...  

[25658 rows x 4 columns]

In [96]:
pd.Series(k)

0        0.1//-0.0//-0.1//0.1//-0.2//-0.0//-0.0//0.1//0...
1        0.1//0.0//-0.1//-0.0//0.0//0.0//0.1//-0.0//0.1...
2        0.1//0.0//0.0//-0.0//0.2//0.0//0.2//-0.1//-0.0...
3        0.1//-0.2//0.1//0.2//-0.3//0.0//-0.0//0.0//-0....
4        -0.1//0.2//0.2//0.1//-0.1//0.0//0.1//-0.1//0.2...
                               ...                        
25651    0.1//0.0//0.1//0.0//0.1//0.0//0.2//-0.1//0.1//...
25652    -0.1//-0.1//0.0//-0.1//-0.0//0.1//0.2//-0.1//-...
25653    -0.1//0.2//0.2//-0.0//0.1//-0.1//0.1//-0.1//0....
25654    -0.0//-0.1//0.1//0.1//-0.3//-0.1//0.0//-0.1//0...
25655    0.1//-0.0//0.1//0.1//-0.0//-0.1//0.0//0.0//-0....
Length: 25656, dtype: object

In [95]:
df_fame.gene_e

0        -0.081911//0.023442//0.118003//-0.118417//0.06...
1        0.068768//-0.010101//-0.121707//0.142479//-0.1...
2        0.094386//0.013693//-0.124994//-0.000583//0.02...
3        0.085143//0.031898//0.043786//-0.038682//0.188...
4        0.111219//-0.157678//0.085092//0.155815//-0.27...
                               ...                        
25653    -0.081926//-0.054207//0.049499//-0.067319//-0....
25654    -0.084058//0.171540//0.165466//-0.043218//0.11...
25655    -0.008801//-0.091641//0.055367//0.077171//-0.2...
25656    0.053546//-0.034953//0.096325//0.090061//-0.02...
25657    0.041853//0.010516//0.050944//0.091727//-0.034...
Name: gene_e, Length: 25658, dtype: object

In [137]:
ene_List = [[float(j) for j in i.split("//")] for i in df_fame.gene_e]

In [298]:
import TransGEM.gene_ex_encoder_upgraded as e
tenfold_binary(ene_List[0], decimal_points=6)

ValueError: invalid literal for int() with base 10: 'b'

In [303]:
def tenfold_binary(gene_e: list, decimal_points: int=1, max_int: int=15, decimals_to_int: int=1) -> np.array:
        out=[]
        decimal_points = decimal_points - decimals_to_int
        for sample in gene_e:
            print(sample)
            sample = sample * 10**decimals_to_int
            sample=float(f"%.{decimal_points}f" % sample)
            int_lenth = len(bin(max_int*(10**decimals_to_int))[2:])
            bit = 1+int_lenth+4*(decimal_points)
            vector= [0] * bit
            
            if sample > 0:
                vector[0] = 1
            else:
                sample = -sample
            
            vector[1+int_lenth-len(bin(int(sample))[2:]):int_lenth+1] = [int(j) for j in bin(int(sample))[2:]]

            
            for decimal in range(1, decimal_points+1):
                if sample*decimal - int(sample*decimal) != 0:
                    value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                    index_begin = (1+int_lenth+4*decimal) - len(bin(value)[2:])
                    index_end = (1+int_lenth+4*decimal)
                    vector[index_begin:index_end] = [int(j) for j in bin(int(value))[2:]]

            out.append(vector)
        return np.array(out)



tenfold_binary([-0.02875], decimal_points=6)

-0.02875


ValueError: invalid literal for int() with base 10: 'b'

In [284]:
v = 23442.0
decimal_points = -1
sample=float(f"%.{decimal_points}f" % v)
sample

ValueError: unsupported format character '-' (0x2d) at index 2

150


ValueError: unsupported format character '-' (0x2d) at index 2

In [204]:
e.one_hot([0.03634], decimal_points=6)

0.03634


IndexError: list assignment index out of range

In [261]:
import numpy as np

def one_hot(gene_e: list, decimal_points: int=1, max_int_size: int=15, numbers_size: int=9) -> np.array:
        out=[]
        for sample in gene_e:
             bit = (1+15+numbers_size*decimal_points+1)
             sample = float(f"%.{decimal_points}f" % sample)
             vector = [0]*bit

             if sample > 0:
                 vector[0] = 1
             else:
                  sample = -sample

             vector[abs(int(sample)-max_int_size)+1] = 1

             for decimal in range(1, decimal_points+1):
                    if sample*decimal - int(sample*decimal) != 0:
                       if (sample*10**decimal - int(sample*10**decimal) >= 0.99):
                          value = int(round(sample*10**decimal) - round(sample*10**(decimal-1))*10)
                       else:
                          value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                       if value != 10:
                        index = 1+max_int_size+numbers_size*(decimal-1)+value
                        vector[index] = 1

             out.append(vector)

        return np.array(out)

n = 0.03634
# n = 0.0003
# n = 0.00091
r = one_hot([n], decimal_points=6)
# print('----------------------------')
# one_hot([0.036333], decimal_points=6)
# print('----------------------------')
# one_hot([0.036343], decimal_points=6)
print(r[0][17:17+9])
print(r[0][17+9:17+9*2])
print(r[0][17+9*2:17+9*3])
print(r[0][17+9*3:17+9*4])
print(r[0][17+9*4:17+9*5])
print(r[0][17+9*5:17+9*6])
# print(r[0][17+9*6:17+9*7])

print(n)

[0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0]
[0 0 1 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]
0.03634


In [222]:
r

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0]])

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])