In [ ]:

import pandas as pd

df=pd.read_csv('./data/subLINCS_test.csv')

In [3]:
df

cell_line   dose        drug_id  \
0       MCF7  10 uM  BRD-K41895714   
1        PC3  10 uM  BRD-K41859756   
2       A549  10 uM  BRD-A22684332   
3       A375  10 uM  BRD-K33226500   
4       HT29  10 uM  BRD-K07691486   
5       HA1E  10 uM  BRD-K54708045   
6     MCF10A  10 uM  BRD-K49810818   
7       YAPC  10 uM  BRD-K41895714   
8       HELA  10 uM  BRD-K51544265   
9   MDAMB231  10 uM  BRD-K04923131   
10    HEK293  10 uM  BRD-K53414658   
11      THP1  10 uM  BRD-K87782578   
12    JURKAT  10 uM  BRD-K16730910   
13     HEPG2  10 uM  BRD-K14920963   

                                               smiles  \
0                    O=C1NC(=O)C(S1)=C/c1ccc2nccnc2c1   
1   CCNC(=O)c1noc(c1-c1ccc(CN2CCOCC2)cc1)-c1cc(C(C...   
2             CCC(NC(C)C)C(O)c1ccc(O)c2[nH]c(=O)ccc12   
3   CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...   
4        CC[C@H](CO)Nc1nc(NCc2ccccc2)c2ncn(C(C)C)c2n1   
5     OC(=O)c1n(Cc2ccc(Cl)cc2)c2ccc(Cl)cc2c1Sc1ccccc1   
6   CNC(=O)c1cccc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(c3)C(F)...   
7                    O=C1NC(=O)C(S1)=C/c1ccc2nccnc2c1   
8   COc1cc2nccc(Oc3ccc(NC(=O)C4(CC4)C(=O)Nc4ccc(F)...   
9          ON=C1/C(Nc2ccccc12)=C1/C(=O)Nc2cc(Br)ccc12   
10  COc1cc2nccc(Oc3ccc(NC(=O)Nc4cc(C)on4)c(Cl)c3)c...   
11  COCCOc1ccc(Nc2ncc(F)c(Nc3cccc(NC(=O)C=C)c3)n2)cc1   
12  CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(c3)C(F)(F...   
13  OC(=O)c1ccccc1-c1c2cc(I)c(O)c(I)c2oc2c(I)c(=O)...   

                                              selfies  \
0   ['[O]', '[=C]', '[N]', '[C]', '[Branch1_2]', '...   
1   ['[C]', '[C]', '[N]', '[C]', '[Branch1_2]', '[...   
2   ['[C]', '[C]', '[C]', '[Branch1_1]', '[Branch1...   
3   ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   
4   ['[C]', '[C]', '[C@Hexpl]', '[Branch1_1]', '[R...   
5   ['[O]', '[C]', '[Branch1_2]', '[C]', '[=O]', '...   
6   ['[C]', '[N]', '[C]', '[Branch1_2]', '[C]', '[...   
7   ['[O]', '[=C]', '[N]', '[C]', '[Branch1_2]', '...   
8   ['[C]', '[O]', '[C]', '[=C]', '[C]', '[=N]', '...   
9   ['[O]', '[N]', '[=C]', '[/C]', '[Branch1_1]', ...   
10  ['[C]', '[O]', '[C]', '[=C]', '[C]', '[=N]', '...   
11  ['[C]', '[O]', '[C]', '[C]', '[O]', '[C]', '[=...   
12  ['[C]', '[N]', '[C]', '[Branch1_2]', '[C]', '[...   
13  ['[O]', '[C]', '[Branch1_2]', '[C]', '[=O]', '...   

                                               gene_e  
0   0.0//0.0//0.1//0.2//-0.0//-0.3//0.0//0.0//-0.1...  
1   -0.0//0.3//0.1//0.3//-0.3//-0.1//0.2//-0.4//0....  
2   0.1//0.1//-0.0//-0.0//0.2//-0.3//-0.1//0.0//0....  
3   -0.1//-0.2//0.0//0.0//0.1//-0.0//0.0//-0.1//-0...  
4   -0.1//-0.0//-0.2//0.2//0.1//-0.1//-0.2//0.1//0...  
5   0.2//0.2//0.3//0.2//0.3//-0.0//-0.0//0.1//-0.0...  
6   0.0//-0.7//-0.0//-0.1//-0.2//0.3//0.0//0.5//-0...  
7   0.0//-0.3//-0.1//-0.4//0.1//-0.1//0.1//0.1//0....  
8   0.3//0.3//0.1//0.1//0.7//0.0//-0.0//-0.3//-0.0...  
9   1.1//0.2//-0.4//0.6//-0.4//0.4//-0.6//0.3//-0....  
10  0.3//-0.1//0.0//-0.3//-0.3//0.0//0.1//-0.2//-0...  
11  0.7//-0.0//0.0//0.3//-0.7//-0.2//0.3//0.1//0.1...  
12  0.1//-0.2//0.0//0.5//0.1//-0.1//-0.0//0.1//0.0...  
13  0.0//0.0//0.1//-2.6//-0.0//0.7//0.0//4.6//0.0/...

In [6]:
df.gene_e[0]

'0.0//0.0//0.1//0.2//-0.0//-0.3//0.0//0.0//-0.1//-0.0//0.1//0.1//0.1//-0.1//0.1//0.1//-0.1//-0.0//0.1//-0.1//-0.0//-0.0//-0.1//-0.0//0.1//-0.0//0.1//0.1//0.0//-0.0//-0.2//-0.3//-0.4//0.1//-0.1//-0.3//-0.3//0.1//0.1//0.0//0.1//0.2//-0.1//0.0//0.1//0.1//0.1//0.0//-0.2//-0.1//-0.1//-0.0//-0.0//0.2//0.1//0.1//-0.0//-0.1//-0.1//0.0//-0.1//-0.1//-0.1//-0.2//0.1//0.0//0.1//-0.2//0.0//-0.0//-0.1//-0.3//0.1//-0.0//0.1//-0.1//-0.0//-0.0//0.0//-0.0//-0.0//-0.3//0.0//0.1//-0.2//-0.1//0.2//0.0//0.2//-0.2//0.0//0.3//0.1//0.1//-0.2//0.0//0.0//0.1//-0.3//0.0//0.1//0.1//0.1//-0.2//-0.1//-0.0//0.1//0.0//-0.0//-0.1//0.1//0.3//-0.1//0.2//-0.0//0.0//0.0//0.0//-0.3//0.0//-0.1//0.1//0.2//-0.1//-0.4//-0.1//-0.0//-0.1//0.0//0.0//0.0//-0.0//-0.1//-0.1//-0.2//-0.2//-0.0//0.0//-0.2//-0.0//-0.1//-0.1//0.0//0.1//0.2//-0.1//0.0//0.1//0.2//0.1//-0.1//0.1//0.1//-0.1//0.2//0.2//0.0//0.1//-0.0//0.2//0.1//0.0//0.1//-0.1//0.2//-0.1//-0.1//-0.1//0.0//0.2//0.1//0.1//0.1//-0.2//-0.3//0.0//0.0//0.0//0.1//-0.1//0.1//0.4//0.2//

In [ ]:
for i in df.iloc[0, -3:-1]:
    print(i)

O=C1NC(=O)C(S1)=C/c1ccc2nccnc2c1
['[O]', '[=C]', '[N]', '[C]', '[Branch1_2]', '[C]', '[=O]', '[C]', '[Branch1_1]', '[Ring2]', '[S]', '[Ring1]', '[Branch1_2]', '[=C]', '[/C]', '[=C]', '[C]', '[=C]', '[N]', '[=C]', '[C]', '[=N]', '[C]', '[Ring1]', '[Branch1_2]', '[=C]', '[Ring1]', '[Branch2_3]']


In [ ]:
len(df.gene_e.str.split('//')[10])

978

In [18]:
df

cell_line   dose        drug_id  \
0       MCF7  10 uM  BRD-K41895714   
1        PC3  10 uM  BRD-K41859756   
2       A549  10 uM  BRD-A22684332   
3       A375  10 uM  BRD-K33226500   
4       HT29  10 uM  BRD-K07691486   
5       HA1E  10 uM  BRD-K54708045   
6     MCF10A  10 uM  BRD-K49810818   
7       YAPC  10 uM  BRD-K41895714   
8       HELA  10 uM  BRD-K51544265   
9   MDAMB231  10 uM  BRD-K04923131   
10    HEK293  10 uM  BRD-K53414658   
11      THP1  10 uM  BRD-K87782578   
12    JURKAT  10 uM  BRD-K16730910   
13     HEPG2  10 uM  BRD-K14920963   

                                               smiles  \
0                    O=C1NC(=O)C(S1)=C/c1ccc2nccnc2c1   
1   CCNC(=O)c1noc(c1-c1ccc(CN2CCOCC2)cc1)-c1cc(C(C...   
2             CCC(NC(C)C)C(O)c1ccc(O)c2[nH]c(=O)ccc12   
3   CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...   
4        CC[C@H](CO)Nc1nc(NCc2ccccc2)c2ncn(C(C)C)c2n1   
5     OC(=O)c1n(Cc2ccc(Cl)cc2)c2ccc(Cl)cc2c1Sc1ccccc1   
6   CNC(=O)c1cccc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(c3)C(F)...   
7                    O=C1NC(=O)C(S1)=C/c1ccc2nccnc2c1   
8   COc1cc2nccc(Oc3ccc(NC(=O)C4(CC4)C(=O)Nc4ccc(F)...   
9          ON=C1/C(Nc2ccccc12)=C1/C(=O)Nc2cc(Br)ccc12   
10  COc1cc2nccc(Oc3ccc(NC(=O)Nc4cc(C)on4)c(Cl)c3)c...   
11  COCCOc1ccc(Nc2ncc(F)c(Nc3cccc(NC(=O)C=C)c3)n2)cc1   
12  CNC(=O)c1cc(Oc2ccc(NC(=O)Nc3ccc(Cl)c(c3)C(F)(F...   
13  OC(=O)c1ccccc1-c1c2cc(I)c(O)c(I)c2oc2c(I)c(=O)...   

                                              selfies  \
0   ['[O]', '[=C]', '[N]', '[C]', '[Branch1_2]', '...   
1   ['[C]', '[C]', '[N]', '[C]', '[Branch1_2]', '[...   
2   ['[C]', '[C]', '[C]', '[Branch1_1]', '[Branch1...   
3   ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   
4   ['[C]', '[C]', '[C@Hexpl]', '[Branch1_1]', '[R...   
5   ['[O]', '[C]', '[Branch1_2]', '[C]', '[=O]', '...   
6   ['[C]', '[N]', '[C]', '[Branch1_2]', '[C]', '[...   
7   ['[O]', '[=C]', '[N]', '[C]', '[Branch1_2]', '...   
8   ['[C]', '[O]', '[C]', '[=C]', '[C]', '[=N]', '...   
9   ['[O]', '[N]', '[=C]', '[/C]', '[Branch1_1]', ...   
10  ['[C]', '[O]', '[C]', '[=C]', '[C]', '[=N]', '...   
11  ['[C]', '[O]', '[C]', '[C]', '[O]', '[C]', '[=...   
12  ['[C]', '[N]', '[C]', '[Branch1_2]', '[C]', '[...   
13  ['[O]', '[C]', '[Branch1_2]', '[C]', '[=O]', '...   

                                               gene_e  
0   0.0//0.0//0.1//0.2//-0.0//-0.3//0.0//0.0//-0.1...  
1   -0.0//0.3//0.1//0.3//-0.3//-0.1//0.2//-0.4//0....  
2   0.1//0.1//-0.0//-0.0//0.2//-0.3//-0.1//0.0//0....  
3   -0.1//-0.2//0.0//0.0//0.1//-0.0//0.0//-0.1//-0...  
4   -0.1//-0.0//-0.2//0.2//0.1//-0.1//-0.2//0.1//0...  
5   0.2//0.2//0.3//0.2//0.3//-0.0//-0.0//0.1//-0.0...  
6   0.0//-0.7//-0.0//-0.1//-0.2//0.3//0.0//0.5//-0...  
7   0.0//-0.3//-0.1//-0.4//0.1//-0.1//0.1//0.1//0....  
8   0.3//0.3//0.1//0.1//0.7//0.0//-0.0//-0.3//-0.0...  
9   1.1//0.2//-0.4//0.6//-0.4//0.4//-0.6//0.3//-0....  
10  0.3//-0.1//0.0//-0.3//-0.3//0.0//0.1//-0.2//-0...  
11  0.7//-0.0//0.0//0.3//-0.7//-0.2//0.3//0.1//0.1...  
12  0.1//-0.2//0.0//0.5//0.1//-0.1//-0.0//0.1//0.0...  
13  0.0//0.0//0.1//-2.6//-0.0//0.7//0.0//4.6//0.0/...

In [ ]:
pd.read_csv('./data/subLINCS_train.csv')

cell_line   dose        drug_id  \
0          MCF7  10 uM  BRD-A60070924   
1          MCF7  10 uM  BRD-K71879491   
2          MCF7  10 uM  BRD-K43797669   
3          MCF7  10 uM  BRD-A13084692   
4          MCF7  10 uM  BRD-K41260949   
...         ...    ...            ...   
25359     HEPG2  10 uM  BRD-K30421593   
25360     HEPG2  10 uM  BRD-K40472535   
25361     HEPG2  10 uM  BRD-K13049116   
25362     HEPG2  10 uM  BRD-K19894101   
25363     HEPG2  10 uM  BRD-K86574132   

                                                  smiles  \
0                       CC12CCC3C(CCc4cc(O)ccc34)C1CCC2O   
1             CC(/C=C/C1=C(C)CCCC1(C)C)=CC=CC(C)=CC(O)=O   
2                     Oc1ccc(cc1)-c1coc2cc(O)cc(O)c2c1=O   
3      Cc1c(C)c2OC(C)(COc3ccc(CC4SC(=O)NC4=O)cc3)CCc2...   
4                                        CCCC(CCC)C(O)=O   
...                                                  ...   
25359               CC(C)(C)NC[C@@H](O)COc1nsnc1N1CCOCC1   
25360  C[C@@H](CO)N1C[C@H](C)[C@@H](CN(C)Cc2ccncc2)OC...   
25361  C[C@]1(CCCN1c1nc(Nc2cc(n[nH]2)C2CC2)c2cccn2n1)...   
25362     Oc1cccc(C(=O)Nc2cccc(NC(=O)c3cccc(O)c3O)c2)c1O   
25363  CC(C)N1C(=O)S/C(=C/c2ccc(Sc3nc4ccccc4[nH]3)o2)...   

                                                 selfies  \
0      ['[C]', '[C]', '[C]', '[C]', '[C]', '[C]', '[B...   
1      ['[C]', '[C]', '[Branch2_1]', '[Ring1]', '[C]'...   
2      ['[O]', '[C]', '[=C]', '[C]', '[=C]', '[Branch...   
3      ['[C]', '[C]', '[=C]', '[Branch1_1]', '[C]', '...   
4      ['[C]', '[C]', '[C]', '[C]', '[Branch1_1]', '[...   
...                                                  ...   
25359  ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   
25360  ['[C]', '[C@@Hexpl]', '[Branch1_1]', '[Ring1]'...   
25361  ['[C]', '[C@expl]', '[Branch2_1]', '[Ring2]', ...   
25362  ['[O]', '[C]', '[=C]', '[C]', '[=C]', '[C]', '...   
25363  ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   

                                                  gene_e  
0      -0.1//-0.3//-0.2//0.1//0.1//-0.1//-0.2//0.0//0...  
1      0.3//0.1//0.1//0.0//-0.3//-0.4//0.2//-0.3//0.2...  
2      0.0//0.1//-0.4//0.0//0.2//-0.1//-0.1//-0.1//-0...  
3      0.3//-0.0//-0.0//0.1//0.0//-0.1//-0.0//-0.1//-...  
4      -0.1//-0.3//-0.0//0.1//-0.0//0.1//0.1//0.1//0....  
...                                                  ...  
25359  0.0//0.1//0.0//-0.5//0.1//-0.1//-0.2//-0.2//-0...  
25360  0.1//-0.1//-0.2//0.2//0.1//0.4//0.5//0.1//0.2/...  
25361  0.5//0.3//0.4//-0.3//-2.0//-0.3//0.2//-0.2//-0...  
25362  -0.0//0.1//0.7//-1.0//-1.4//-0.8//0.9//-1.1//-...  
25363  1.2//0.0//0.3//-1.3//-3.2//0.0//0.4//-0.6//-0....  

[25364 rows x 6 columns]

## Predicted

In [ ]:
import pandas as pd

df=pd.read_csv('../test_subLINCS_tenfold_binary.csv')

In [6]:
df.preds.apply(len)

0     145923
1     163839
2     150920
3     158447
4     164381
5     173175
6     203812
7     184609
8     184242
9     159721
10    150864
11    194257
12    161295
13    179700
Name: preds, dtype: int64

In [7]:
df

ID                                              preds  valid  \
0    sample0  ['C=12OC=CC=1COC2OO', 'N1C(=O)C=C1C=CC=CC=CC2=...    1.0   
1    sample1  ['C=12OC=CC=1COC2OO', 'C12C3=CC=C1C=C23', 'C=1...    1.0   
2    sample2  ['C=12OC=CC=1COC2OO', 'OC(=O)C=O', 'N1C(=O)C=C...    1.0   
3    sample3  ['C=12OC=CC=1COC2OO', 'C=12OC=CC=1C=C2OO', 'N1...    1.0   
4    sample4  ['C=12OC=CC=1COC2OO', 'C=12OC=CC=1C=C2OO', 'N1...    1.0   
5    sample5  ['C=12OC=CC=1COC2OO', 'C12C3=CC=C1C=C23', 'C=1...    1.0   
6    sample6  ['C=12OC=CC=1COC2OO', 'C12C3=CC=C1C=C23', 'C=1...    1.0   
7    sample7  ['C=12OC=CC=1COC2OO', 'C12C3=CC=C1C=C23', 'N1C...    1.0   
8    sample8  ['C=12OC=CC=1COC2OO', 'C12C3=CC=C1C=C23', 'C=1...    1.0   
9    sample9  ['C=12OC=CC=1COC2OO', 'C=12OC=CC=1C=C2OO', 'C1...    1.0   
10  sample10  ['C=12OC=CC=1COC2OO', 'C12C3=CC=C1C=C23', 'C=1...    1.0   
11  sample11  ['C=12OC=CC=1COC2OO', 'C=12OC=CC=1C=C2OO', 'C1...    1.0   
12  sample12  ['C=12OC=CC=1COC2OO', 'N1C(=O)C=C1C=CC=CC=CC2=...    1.0   
13  sample13  ['C=12OC=CC=1COC2OO', 'N1C(=O)C=C1C=CC=CC=CC2=...    1.0   

      unique       div   qed_mid  \
0   0.814667  0.787722  0.910167   
1   0.878000  0.796081  0.893647   
2   0.803333  0.800673  0.910167   
3   0.825333  0.797165  0.888588   
4   0.847000  0.805139  0.893881   
5   0.848667  0.799957  0.888588   
6   0.850333  0.795164  0.885751   
7   0.833667  0.791987  0.902380   
8   0.866667  0.787225  0.897344   
9   0.898000  0.753238  0.892051   
10  0.823667  0.788174  0.897344   
11  0.851333  0.784605  0.886797   
12  0.819667  0.782023  0.884544   
13  0.876333  0.785090  0.887909   

                                                  qed   mw_mid  \
0   [0.9394609188372363, 0.9292842579546593, 0.929...  596.488   
1   [0.928697108212548, 0.90497365509213, 0.901250...  808.227   
2   [0.9394609188372363, 0.9292842579546593, 0.929...  610.515   
3   [0.9292842579546593, 0.928697108212548, 0.9153...  610.515   
4   [0.9292842579546593, 0.928697108212548, 0.9153...  677.254   
5   [0.928697108212548, 0.9153597050850025, 0.9049...  729.922   
6   [0.928697108212548, 0.8949022842019841, 0.8891...  893.312   
7   [0.9394609188372363, 0.9292842579546593, 0.928...  729.922   
8   [0.928697108212548, 0.9153597050850025, 0.9049...  739.961   
9   [0.9292842579546593, 0.928697108212548, 0.9049...  889.280   
10  [0.9394609188372363, 0.9292842579546593, 0.928...  988.933   
11  [0.8997858585104801, 0.8949022842019841, 0.889...  756.004   
12  [0.9394609188372363, 0.9292842579546593, 0.904...  677.758   
13  [0.9292842579546593, 0.90497365509213, 0.89978...  612.531   

                                                   mw    sa_mid  \
0   [610.5150000000002, 596.4880000000003, 596.488...  1.530341   
1   [827.2089999999998, 817.2139999999998, 817.213...  1.568118   
2   [624.5860000000001, 624.586, 624.586, 623.578,...  1.563203   
3   [624.586, 624.586, 623.578, 623.578, 610.51500...  1.563203   
4   [729.9219999999992, 729.9219999999992, 703.839...  1.530341   
5   [756.0039999999991, 756.0039999999991, 739.960...  1.553127   
6   [921.366, 905.323, 893.3119999999999, 893.3119...  1.568118   
7   [729.9219999999992, 729.9219999999992, 729.921...  1.563203   
8   [756.0039999999991, 756.0039999999991, 756.003...  1.563203   
9   [889.2799999999999, 889.2799999999999, 889.279...  1.568809   
10  [1035.0019999999995, 990.9489999999997, 990.94...  1.568118   
11  [759.0899999999999, 756.0039999999991, 756.003...  1.568118   
12  [703.8399999999993, 703.8399999999992, 703.839...  1.568118   
13  [703.8399999999992, 637.6490000000003, 623.622...  1.568118   

                                                   sa  
0   [1.0, 1.0, 1.3892838691001437, 1.4454245361345...  
1   [1.0, 1.3892838691001437, 1.4989832128293603, ...  
2   [1.0, 1.3892838691001437, 1.4454245361345155, ...  
3   [1.0, 1.3892838691001437, 1.4454245361345155, ...  
4   [1.0, 1.1897575478356917, 1.3892838691001437, ...  
5   [1.0, 1.0, 1.38928386

# Testing the embeddings

In [ ]:
import pandas as pd


a = pd.read_csv('data/FAME_dataset_val.csv')
a = a.iloc[:,1:]
a.to_csv('data/2_FAME_dataset_val.csv', index=False)

array([-0.14725 ,  0.09189 ,  0.306283, -0.063744,  0.130812, -0.11615 ,
        0.078119,  0.075412,  0.039793, -0.053242, -0.00215 ,  0.015879,
        0.00105 ,  0.009904,  0.079167, -0.036272,  0.108092,  0.065498,
        0.016189, -0.181391,  0.036978, -0.080123, -0.175596,  0.202938,
        0.199309,  0.016509,  0.105856, -0.030473, -0.210702, -0.117647,
       -0.154936,  0.067644,  0.406332, -0.095251, -0.010657, -0.06429 ,
        0.009327, -0.118693,  0.068488, -0.057034,  0.060365, -0.007333,
       -0.060138,  0.059936,  0.030228,  0.041317, -0.035899, -0.033037,
        0.195254, -0.082098,  0.145338, -0.003132, -0.073925,  0.05377 ,
       -0.131844, -0.162536, -0.032311, -0.217758,  0.035299, -0.116958,
       -0.141407, -0.002195, -0.064869,  0.017028])

In [ ]:
def value(gene_e):
        out=[]
        for i in gene_e:
            i=float("%.5f" % i)
            a=[i]
            out.append(a)
        return np.array(out)

In [64]:
a

array([-0.14725 ,  0.09189 ,  0.306283, -0.063744,  0.130812, -0.11615 ,
        0.078119,  0.075412,  0.039793, -0.053242, -0.00215 ,  0.015879,
        0.00105 ,  0.009904,  0.079167, -0.036272,  0.108092,  0.065498,
        0.016189, -0.181391,  0.036978, -0.080123, -0.175596,  0.202938,
        0.199309,  0.016509,  0.105856, -0.030473, -0.210702, -0.117647,
       -0.154936,  0.067644,  0.406332, -0.095251, -0.010657, -0.06429 ,
        0.009327, -0.118693,  0.068488, -0.057034,  0.060365, -0.007333,
       -0.060138,  0.059936,  0.030228,  0.041317, -0.035899, -0.033037,
        0.195254, -0.082098,  0.145338, -0.003132, -0.073925,  0.05377 ,
       -0.131844, -0.162536, -0.032311, -0.217758,  0.035299, -0.116958,
       -0.141407, -0.002195, -0.064869,  0.017028])

In [65]:
p

array([[-0.14725],
       [ 0.09189],
       [ 0.30628],
       [-0.06374],
       [ 0.13081],
       [-0.11615],
       [ 0.07812],
       [ 0.07541],
       [ 0.03979],
       [-0.05324],
       [-0.00215],
       [ 0.01588],
       [ 0.00105],
       [ 0.0099 ],
       [ 0.07917],
       [-0.03627],
       [ 0.10809],
       [ 0.0655 ],
       [ 0.01619],
       [-0.18139],
       [ 0.03698],
       [-0.08012],
       [-0.1756 ],
       [ 0.20294],
       [ 0.19931],
       [ 0.01651],
       [ 0.10586],
       [-0.03047],
       [-0.2107 ],
       [-0.11765],
       [-0.15494],
       [ 0.06764],
       [ 0.40633],
       [-0.09525],
       [-0.01066],
       [-0.06429],
       [ 0.00933],
       [-0.11869],
       [ 0.06849],
       [-0.05703],
       [ 0.06036],
       [-0.00733],
       [-0.06014],
       [ 0.05994],
       [ 0.03023],
       [ 0.04132],
       [-0.0359 ],
       [-0.03304],
       [ 0.19525],
       [-0.0821 ],
       [ 0.14534],
       [-0.00313],
       [-0.0

## Creatng new embeddings to the new data

In [ ]:
from TransGEM import gene_ex_encoder as gene_enc
import numpy as np
import pandas as pd
import math

df_fame = pd.read_csv('data/FAME_dataset_val.csv')
df_trans = pd.read_csv('data/subLINCS_val.csv')


In [5]:
def value(gene_e, decimal_points=5):
        out=[]
        for i in gene_e:
            i=float(f"%.{decimal_points}f" % i)
            a=[i]
            out.append(a)
        return np.array(out)


fame_sample = np.array(df_fame['gene_e'].str.split('//')[0]).astype('float')
fame_to_value = value(fame_sample)

trans_sample = np.array(df_trans['gene_e'].str.split('//')[0]).astype('float')
trans_to_value = gene_enc.value(trans_sample)

In [6]:
# f'%.2f'
i = -3.43


decimal_points = 3


# sample = float(f"%.{decimal_points}f")
i=float(f"%.{decimal_points}f" % i)
# sample
i

-3.43

### One Hot

In [ ]:
def one_hot(gene_e,bit=25, t=10):
        out=[]
        for i in gene_e:
            i=float("%.5f" % i)
            a=[0]*bit
            if i>0:
                a[0]=1
                a[int(i)] = 1
                if i-int(i)!=0:
                    print(int(i*t-int(i)*t)+15)
                    a[int(i*t-int(i)*t)+15] = 1
                # if i-int(i)-
            if i<0:
                
                a[abs(int(i))] = 1
                if i-int(i)!=0:
                    a[abs(int(i*t-int(i)*t))+15] = 1
            out.append(a)
        return np.array(out)

def one_hot_local_two_digits(i,bit=(1+15+9+9), t=[10, 100], max_int_size=15, numbers_size=9):
        i=float("%.5f" % i)
        a=[0]*bit
        if i>0:
            a[0]=1
            a[int(i)] = 1
            if i-int(i)!=0:
                print(int(i*t[0]-int(i)*t[0]))
                a[int(i*t[0]-int(i)*t[0])+max_int_size] = 1
            print(i*t[0] - int(i*t[0]))
            if (i*t[0] - int(i*t[0])) != 0:
                print(int(i*t[1]-int(i*t[0])*t[0]))
                a[int(i*t[1]-int(i*t[0])*t[0])+max_int_size+numbers_size] = 1
        if i<0:
                
            a[abs(int(i))] = 1
            if i-int(i)!=0:
                a[abs(int(i*t-int(i)*t))+max_int_size] = 1
        print(np.array(a))

def one_hot_local_each_gene(i, decimal_points=3, t=10, max_int_size=15, numbers_size=9):
        bit = (1+15+numbers_size*decimal_points+1)
        i=float(f"%.{decimal_points}f" % i)
        a=[0]*bit
        if i > 0:
            a[0] = 1
        else:
             i = -i
        a[abs(int(i)-max_int_size)+1] = 1
        for decimal in range(1, decimal_points+1):
             if i*decimal - int(i*decimal) != 0:
                  value = int(int(i*10**decimal) - int(i*10**(decimal-1))*10)
                  index = 1+max_int_size+numbers_size*(decimal-1)+value
                  a[index] = 1
        print(np.array(a))





array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [6]:
def one_hot_local(gene_e, decimal_points=3, max_int_size=15, numbers_size=9):
        out=[]

        for sample in gene_e:
             bit = (1+15+numbers_size*decimal_points+1)
             sample = float(f"%.{decimal_points}f" % sample)
             vector = [0]*bit

             if sample > 0:
                 vector[0] = 1
             else:
                  sample = -sample

             vector[abs(int(sample)-max_int_size)+1] = 1

             for decimal in range(1, decimal_points+1):
                  if sample*decimal - int(sample*decimal) != 0:
                       value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                       index = 1+max_int_size+numbers_size*(decimal-1)+value
                       vector[index] = 1

             out.append(vector)

        return np.array(out)



one_hot_local([15.19998, 4.34219], decimal_points=5)

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [71]:
decimal_points = 3
sample = -3.45
float(f"%.{decimal_points}f" % sample)

-3.45

## Binary

In [7]:
trans_to_binary = gene_enc.binary([-15.9, 0.3])
print(trans_to_binary[0])
print(trans_to_binary[0])
2**len(trans_to_binary[1])


print(trans_to_binary[0][1:5])
print(trans_to_binary[0][6:])

[0 0 1 1 1 1 1 0 0 1]
[0 0 1 1 1 1 1 0 0 1]
[0 1 1 1]
[1 0 0 1]


In [284]:
trans_to_binary = gene_enc.tenfold_binary([-15.9, 0.3])
print(trans_to_binary[0])
print(trans_to_binary[0])
2**len(trans_to_binary[1])
# 159 128 + 16 + 8+4+2+1

print(trans_to_binary[0][1:5])
print(trans_to_binary[0][6:])

[0 1 0 0 1 1 1 1 1]
[0 1 0 0 1 1 1 1 1]
[1 0 0 1]
[1 1 1]


In [287]:
bin(int(12))

'0b1100'

In [8]:
def binary(gene_e,bit=10, t=10, decimal_points=3):
        out=[]
        for i in gene_e:
            i=float(f"%.{decimal_points}f" % i)
            a=[0]*bit
            if i>0:
                a[0]=1
                a[6-len(bin(int(i))[2:]):6] = [int(j) for j in bin(int(i))[2:]]
                if i-int(i)!=0:
                    ii=int(i*t-int(i)*t)
                    a[-len(bin(int(ii))[2:]):] = [int(j) for j in bin(int(ii))[2:]]
            if i<0:
                
                a[6-len(bin(int(i))[3:]):6] = [int(j) for j in bin(int(i))[3:]]
                if i-int(i)!=0:
                    ii=int(i*t-int(i)*t)
                    a[-len(bin(int(ii))[3:]):] = [int(j) for j in bin(int(ii))[3:]]
            out.append(a)
        return np.array(out)

def binary_local(gene_e, decimal_points=3):
        out=[]
        for sample in gene_e:
            sample=float(f"%.{decimal_points}f" % sample)
            bit = (1+5+4*decimal_points)
            vector= [0] * bit
            
            if sample > 0:
                vector[0] = 1
            else:
                sample = -sample
            
            vector[6-len(bin(int(sample))[2:]):6] = [int(j) for j in bin(int(sample))[2:]]

            
            for decimal in range(1, decimal_points+1):
                if sample*decimal - int(sample*decimal) != 0:
                    value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                    index_begin = (6+4*decimal) - len(bin(value)[2:])
                    index_end = (6+4*decimal)
                    vector[index_begin:index_end] = [int(j) for j in bin(int(value))[2:]]

            out.append(vector)
        return np.array(out)


binary_local([1.9373], decimal_points=4)

array([[1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1]])

## Ten-folder

In [15]:
len(bin(15*10)[2:])

8

In [ ]:
def ten_folder_binary_local_only_ten(gene_e, decimal_points=3, max_int = 15):
        out=[]
        for sample in gene_e:
            sample = sample * 10
            decimal_points = decimal_points - 1
            sample=float(f"%.{decimal_points}f" % sample)
            int_lenth = len(bin(max_int*10)[2:])
            bit = 1+int_lenth+4*(decimal_points)
            vector= [0] * bit
            
            if sample > 0:
                vector[0] = 1
            else:
                sample = -sample
            
            vector[1+int_lenth-len(bin(int(sample))[2:]):int_lenth+1] = [int(j) for j in bin(int(sample))[2:]]

            
            for decimal in range(1, decimal_points+1):
                if sample*decimal - int(sample*decimal) != 0:
                    value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                    index_begin = (1+int_lenth+4*decimal) - len(bin(value)[2:])
                    index_end = (1+int_lenth+4*decimal)
                    vector[index_begin:index_end] = [int(j) for j in bin(int(value))[2:]]

            out.append(vector)
        return np.array(out)



def ten_folder_binary_local(gene_e, decimal_points=3, max_int = 15, decimals_to_int=1):
        out=[]
        for sample in gene_e:
            sample = sample * 10**decimals_to_int
            decimal_points = decimal_points - decimals_to_int
            sample=float(f"%.{decimal_points}f" % sample)
            int_lenth = len(bin(max_int*(10**decimals_to_int))[2:])
            bit = 1+int_lenth+4*(decimal_points)
            vector= [0] * bit
            
            if sample > 0:
                vector[0] = 1
            else:
                sample = -sample
            
            vector[1+int_lenth-len(bin(int(sample))[2:]):int_lenth+1] = [int(j) for j in bin(int(sample))[2:]]

            
            for decimal in range(1, decimal_points+1):
                if sample*decimal - int(sample*decimal) != 0:
                    value = int(int(sample*10**decimal) - int(sample*10**(decimal-1))*10)
                    index_begin = (1+int_lenth+4*decimal) - len(bin(value)[2:])
                    index_end = (1+int_lenth+4*decimal)
                    vector[index_begin:index_end] = [int(j) for j in bin(int(value))[2:]]

            out.append(vector)
        return np.array(out)


ten_folder_binary_local([-1.1137], decimal_points=4, decimals_to_int=3)

7
16
19


array([[0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1]])

In [ ]:
p = bytearray(b'00010001011001')

# int(p)

1 + 8+ 16+64+1024


1113

In [59]:
bin(111)

'0b1101111'

In [9]:
trans_sample

array([-0. ,  0.1,  0.1,  0.1,  0.1, -0. ,  0. ,  0.1, -0.1,  0.1,  0.1,
        0. ,  0.2,  0.1, -0.1, -0. , -0.2,  0.2, -0.1, -0.1,  0.1, -0.1,
       -0.1, -0.1,  0.1, -0.1, -0.1,  0. , -0.1, -0.1,  0. , -0. , -0.3,
        0.1, -0.1,  0.1,  0. , -0.1,  0.1, -0.2, -0.1,  0.2, -0. ,  0.1,
        0.1,  0. , -0.1,  0.1,  0. ,  0. ,  0.2,  0. ,  0. , -0.2,  0.1,
        0. , -0.1, -0.2, -0. , -0. , -0.1,  0. , -0.1,  0. , -0.1,  0.3,
       -0.2, -0. ,  0. , -0.1,  0.2,  0.1,  0.1,  0.1, -0.1, -0.2, -0.1,
        0. ,  0. ,  0.1, -0. , -0.3, -0.1,  0.2,  0.2, -0.2, -0. , -0.1,
       -0.2,  0.1, -0.2,  0.1,  0.4, -0.1, -0.2,  0.1, -0.1,  0. , -0.2,
        0.1,  0. , -0. ,  0.1,  0. ,  0.1, -0.1, -0.1,  0.1, -0.2,  0. ,
       -0.1, -0. ,  0.4, -0.1,  0. ,  0.1, -0.1,  0.1, -0. ,  0.2, -0. ,
       -0.2, -0.1, -0. , -0. , -0.2,  0. , -0.1,  0.1,  0.4,  0.1,  0.1,
        0.1, -0. , -0.3, -0. , -0.1, -0.2, -0.1,  0.3, -0. , -0.1,  0.1,
       -0.3, -0.1, -0.2,  0.2,  0.1,  0.4, -0. , -0

In [ ]:
i = 71

print(f'Original TransGEM: {trans_sample[i]}')

print(f'Altered TransGEM: {gene_enc.one_hot(trans_sample)[i]}')

i = 70

print(f'Original TransGEM: {trans_sample[i]}')

print(f'Altered TransGEM: {gene_enc.one_hot(trans_sample)[i]}')
# print(f'Original FAME: {fame_sample[i]}')

# print(f'Altered FAME: {gene_enc.one_hot(fame_sample)[i]}')


Original TransGEM: 0.1
Altered TransGEM: [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
Original TransGEM: 0.2
Altered TransGEM: [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]


In [82]:
gene_enc.one_hot(fame_sample)[0]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0])

## Drafts

In [ ]:
import numpy as np

TGT_stoi=np.load('data/'+"TGT_stoi.npy", allow_pickle=True).item()
TGT_itos=np.load('data/'+"TGT_itos.npy", allow_pickle=True)

In [ ]:
import pandas as pd

pd.read_csv('data/subLINCS_val.csv')

cell_line   dose        drug_id  \
0         MCF7  10 uM  BRD-K33226500   
1         MCF7  10 uM  BRD-K71035033   
2         MCF7  10 uM  BRD-A01320529   
3         MCF7  10 uM  BRD-K55424922   
4         MCF7  10 uM  BRD-K56403959   
...        ...    ...            ...   
1995     HEPG2  10 uM  BRD-K85133207   
1996     HEPG2  10 uM  BRD-K83354763   
1997     HEPG2  10 uM  BRD-K97399794   
1998     HEPG2  10 uM  BRD-A28105619   
1999     HEPG2  10 uM  BRD-K73881242   

                                                 smiles  \
0     CC(C)(C)NC(=O)[C@@H]1CN(Cc2cccnc2)CCN1C[C@@H](...   
1     CN1CCN(Cc2ccc(cc2)C(=O)Nc2ccc(C)c(Nc3nc(cs3)-c...   
2                OCc1cc(ccc1O)C(O)CNCCCCCCOCCCCc1ccccc1   
3                                 Clc1cccc(SC2CCNCC2)n1   
4                  OCCOCCN1CCN(Cc2cccc(Oc3ccccc3)c2)CC1   
...                                                 ...   
1995  CC(=O)N[C@H]1C[C@H](C1)C(=O)Nc1cc(ccc1N)-c1ccc...   
1996                         Cc1ccc(NCCCc2ccccc2)c(N)c1   
1997         Oc1cc(O)c2c(c1)oc(-c1ccc(O)c(O)c1)c(O)c2=O   
1998  CC(C)(O)C=CC(=O)[C@](C)(O)C1[C@H](O)C[C@@]2(C)...   
1999  CCOC(=O)c1c(CSc2ccccc2)n(C)c2cc(Br)c(O)c(CN(C)...   

                                                selfies  \
0     ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   
1     ['[C]', '[N]', '[C]', '[C]', '[N]', '[Branch2_...   
2     ['[O]', '[C]', '[C]', '[=C]', '[C]', '[Branch1...   
3     ['[Cl]', '[C]', '[=C]', '[C]', '[=C]', '[C]', ...   
4     ['[O]', '[C]', '[C]', '[O]', '[C]', '[C]', '[N...   
...                                                 ...   
1995  ['[C]', '[C]', '[Branch1_2]', '[C]', '[=O]', '...   
1996  ['[C]', '[C]', '[=C]', '[C]', '[=C]', '[Branch...   
1997  ['[O]', '[C]', '[=C]', '[C]', '[Branch1_1]', '...   
1998  ['[C]', '[C]', '[Branch1_1]', '[C]', '[C]', '[...   
1999  ['[C]', '[C]', '[O]', '[C]', '[Branch1_2]', '[...   

                                                 gene_e  
0     -0.0//0.1//0.1//0.1//0.1//-0.0//0.0//0.1//-0.1...  
1     0.5//-0.1//-0.1//0.1//0.2//0.0//0.3//-0.0//-0....  
2     0.3//-0.1//-0.5//-0.1//0.8//0.3//0.1//-0.0//-0...  
3     0.0//-0.4//0.2//0.2//0.1//-0.0//-0.1//-0.0//0....  
4     -0.1//-0.0//0.1//0.0//-0.3//0.1//0.1//0.4//-0....  
...                                                 ...  
1995  0.2//-0.2//0.5//-0.1//0.6//1.0//0.0//0.2//0.0/...  
1996  0.4//0.0//0.5//0.2//-0.0//0.2//0.1//0.0//0.0//...  
1997  0.1//0.2//0.3//-0.7//-0.0//0.8//0.2//-0.1//-0....  
1998  0.5//-0.3//0.1//-0.2//-0.2//-0.1//-1.2//-0.8//...  
1999  0.1//-0.1//-0.1//0.5//1.1//0.3//-0.1//-0.1//-0...  

[2000 rows x 6 columns]

In [ ]:
TGT_stoi

{'<pad>': 0,
 '<mask>': 1,
 '<sos>': 2,
 '<eos>': 3,
 '[C]': 4,
 '[=C]': 5,
 '[Ring1]': 6,
 '[Branch1_1]': 7,
 '[Branch1_2]': 8,
 '[N]': 9,
 '[O]': 10,
 '[=O]': 11,
 '[Ring2]': 12,
 '[C@Hexpl]': 13,
 '[C@@Hexpl]': 14,
 '[Branch2_1]': 15,
 '[Branch1_3]': 16,
 '[=N]': 17,
 '[S]': 18,
 '[F]': 19,
 '[Branch2_2]': 20,
 '[#C]': 21,
 '[Branch2_3]': 22,
 '[P]': 23,
 '[Cl]': 24,
 '[Expl=Ring1]': 25,
 '[C@expl]': 26,
 '[#N]': 27,
 '[NHexpl]': 28,
 '[/C]': 29,
 '[C@@expl]': 30,
 '[Br]': 31,
 '[N+expl]': 32,
 '[O-expl]': 33,
 '[Expl=Ring2]': 34,
 '[=S]': 35,
 '.': 36,
 '[I]': 37,
 '[/N]': 38,
 '[S@@expl]': 39,
 '[S@expl]': 40,
 '[=N+expl]': 41,
 '[/S]': 42,
 '[Expl/Ring1]': 43,
 '[Siexpl]': 44,
 '[/C@Hexpl]': 45,
 '[=N-expl]': 46,
 '[2Hexpl]': 47,
 '[/C@@Hexpl]': 48,
 '[B]': 49,
 '[/O]': 50,
 '[#C-expl]': 51}

In [ ]:
from TransGEM import dataset

path = './data/test/'
ge_list=list(df["gene_e"])
cell_line=list(df["cell_line"])
sf_list=list(df["selfies"])
test_dataset= dataset.bulit_test_dataset('./data/test/', 'subLINCS', ge_list, cell_line=cell_line, sf_list=sf_list)

usage: ipykernel_launcher.py [-h] [--data_path DATA_PATH]
                             [--out_path OUT_PATH] [--dataset DATASET]
                             [--gene_encoder GENE_ENCODER] [--gpu GPU]
                             [--hidden_dim HIDDEN_DIM] [--ff_dim FF_DIM]
                             [--PE_dropout PE_DROPOUT]
                             [--TF_dropout TF_DROPOUT] [--TF_N TF_N]
                             [--TF_H TF_H] [--TF_act TF_ACT]
                             [--batch_size BATCH_SIZE] [--epochs EPOCHS]
                             [--lr LR] [--cell_line CELL_LINE]
                             [--pad_idx PAD_IDX] [--start_idx START_IDX]
                             [--end_idx END_IDX] [--max_len MAX_LEN]
                             [--vocab_size VOCAB_SIZE] [--k K] [--alpha ALPHA]
                             [--seq_num SEQ_NUM]
ipykernel_launcher.py: error: argument --ff_dim: invalid int value: 'c:\\Users\\Acer\\AppData\\Roaming\\jupyter\\runtime\\kernel-v3bdd5f

AttributeError: 'tuple' object has no attribute 'tb_frame'